const projects = [
  {
    title: "osu!stego",
    image: "content/media/osu.jpg",
    description: `Master thesis project on implementing steganography into osu!, a popular open-source rhythm game.`,
    year: 2025,
    tags: ["work:university", "tech:c#", "tech:net", "tech:python"],
    repo: "https://github.com/MagisterkaOsu/osu",
  },
  {
    title: "LitterLooter",
    image: "content/media/litterlooter.png",
    description: `Bachelor thesis project on creating a game about cleaning up the environment, Pokémon GO-style.`,
    year: 2023,
    tags: [
      "work:university",
      "tech:react-native",
      "tech:react",
      "tech:typescript",
    ],
    repo: "https://github.com/Inzynierka2024/trash-client",
  },
  {
    title: "tilde-dawn",
    image: "content/media/tilde.jpg",
    description: "Fork of popular startpage tilde, made nicer.",
    year: 2023,
    tags: ["work:personal", "tech:javascript", "tech:html", "tech:css"],
    link: "https://vis256.github.io/tilde-dawn/",
    repo: "https://github.com/vis256/tilde-dawn/",
  },
  {
    title: "inkfind",
    image: "content/media/inkfind2.jpg",
    description: "A tool for finding fountain pen inks by colour.",
    year: 2022,
    tags: ["work:personal", "tech:next.js", "tech:react", "tech:typescript"],
    link: "https://inkfind.vercel.app/",
    repo: "https://github.com/vis256/inkfind/",
  },
  {
    title: "AndroidDeskThing",
    image: "content/media/androiddeskthing.jpg",
    description: "Spotify's Car Thing, but on Android phones.",
    year: 2024,
    tags: [
      "work:university",
      "tech:react-native",
      "tech:react",
      "tech:typescript",
      "tech:python",
      "tech:windows",
    ],
    repo: "https://github.com/vis256/AndroidDeskThing",
  },
  {
    title: "Reverse Engineering Project",
    image: "content/media/reverse.jpg",
    description: "Modding a popular (10M+ downloads) Android application.",
    year: 0,
    tags: ["work:personal", "tech:reverse-engineering", "tech:java"],
  },
  {
    title: "Hexcells Clone",
    image: "content/media/hexcells2.png",
    description: "A clone of the popular Hexcells puzzle game.",
    year: 2021,
    tags: ["work:university", "tech:c", "tech:raylib"],
  },
  {
    title: "Joystick",
    image: "content/media/joystick.png",
    description:
      "Interface for a web-service designed for easily creating internet multiplayer games.",
    year: 2022,
    tags: ["work:akai", "tech:vue", "tech:typescript", "tech:javascript"],
    repo: "https://github.com/akai-org/joystick_monorepo",
  },
  {
    title: "Internet Music Hall",
    image: "content/media/piano.png",
    description: "A virtual music hall.",
    year: 2023,
    tags: ["work:university", "tech:electron", "tech:c++", "tech:javascript"],
    repo: "https://github.com/vis256/SK2-project",
  },
  {
    title: "Magikarp Mayhem",
    image: "content/media/magikarpmayhem.png",
    description: "Social Media for Pokémon trainers.",
    year: 2024,
    tags: ["work:university", "tech:razor", "tech:mvc", "tech:net", "tech:c#"],
    repo: "https://github.com/vis256/MagikarpMayhem",
  },
  {
    title: "Wearable IoT Project",
    image: "content/media/arduino.webp",
    description:
      "Secret project involving wearable IoT, fashion and Bluetooth.",
    year: 0,
    tags: ["work:personal", "tech:c++", "tech:react-native", "tech:react"],
  },
  {
    title: "Kenoma",
    image: "content/media/art-dots-vector.jpg",
    description: "Firefox Mobile fork. Super lightweight and no distractions.",
    year: 0,
    tags: ["work:personal", "tech:javascript", "tech:java"],
  },
];
